const f = ()=>{




try {
    let a = 0
   // console.log(p)
    console.log("program ran sucessfully")
    return
} catch (err) {
    console.log("this is an error")
}

finally{
    console.log("code scripted ")
}
}
f()